# Generated by Django 6.0.5 on 2026-05-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Meilleure vente'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='emoji',
            field=models.CharField(default='📦', max_length=10, verbose_name='Emoji (fallback)'),
        ),
    ]
