# Generated by Django 6.0.5 on 2026-05-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_featured_product_image_alter_product_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=8, unique=True, verbose_name='N° de suivi'),
        ),
    ]
