# Generated by Django 6.0.5 on 2026-05-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_support_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('carte', 'Carte bancaire')], max_length=20, verbose_name='Paiement'),
        ),
    ]
