# Generated by Django 6.0.5 on 2026-05-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_payment_carte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_livraison', 'En livraison'), ('devant_maison', 'Devant chez vous'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
    ]
