# Generated by Django 6.0.5 on 2026-05-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_devant_maison_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('livraison', 'Paiement à la livraison')], max_length=20, verbose_name='Paiement'),
        ),
    ]
