# Generated by Django 6.0.5 on 2026-05-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_simplify_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, verbose_name='Kiosque ouvert')),
                ('opening_hours', models.CharField(default='Lun–Sam : 10h–22h', max_length=200, verbose_name='Horaires')),
                ('closed_msg', models.CharField(default='Le kiosque est actuellement fermé. Revenez bientôt !', max_length=300, verbose_name='Message fermeture')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
