# Generated by Django 6.0.5 on 2026-05-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_site_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_sunday',
            field=models.CharField(default='9h – 14h  &  18h – 3h', max_length=100, verbose_name='Horaires Dimanche'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_week',
            field=models.CharField(default='18h – 3h', max_length=100, verbose_name='Horaires Lun–Sam'),
        ),
    ]
